name: dmi_read
description: "A library for reading .dmi icon files used by the BYOND platform"
version: 0.1.0
author: Dariusz Anzorge <d.anzorge@gmail.com>
homepage: 'https://github.com/DeeUnderscore/dmi_read'

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  image: '^1.1.26'
  archive: '^1.0.27'
  string_scanner: '^1.0.1'

dev_dependencies:
  test: '>=0.12.0'
